openapi: 3.1.1
info:
  title: Alert
  version: 2.0.0
  description: Schema definition for Alert in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Alert:
      x-iri: https://schema.beckn.io/Alert/v2.0
      description: Schema definition for Alert in the Beckn Protocol v2.0.1
      title: Alert
      type: object
      properties:
        affectedEntities:
          description: IDs of entities affected (route/order/fulfillment/etc.)
          type: array
          items:
            type: string
        descriptor:
          $ref: https://schema.beckn.io/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
        id:
          type: string
        severity:
          type: string
        validity:
          $ref: https://schema.beckn.io/TimePeriod/v2.1/attributes.yaml#/components/schemas/TimePeriod
      required:
      - id
      - descriptor
      additionalProperties: false
      x-tags:
      - common
